### ISSUE TITLE
Noob question 

### ISSUE THREAD

**Issue by benevolution** [vagtsal/Weather-Lamp#2]
So I am getting some errors that I dont know how to fix while trying to program the esp8266.  I got openwether api and google maps api codes and put them in the "ID" spot you had at the beginning.  I tried to uncomment the setup functions first but these errors seem to be holding me back.  Can you help walk a noob through getting this worked out?

Arduino: 1.8.5 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 4M (1M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 115200"

sketch_mar02a:55: error: expected ',' or ';' before 'String'
 String username;
 ^
/Users/benevolutionary/Documents/Arduino/sketch_mar02a/sketch_mar02a.ino: In function 'void handleAdminSettings()':
sketch_mar02a:219: error: 'username' was not declared in this scope
     username = server.arg("USERNAME");
     ^
sketch_mar02a:229: error: 'username' was not declared in this scope
   username = eeprom_read_string();
   ^
/Users/benevolutionary/Documents/Arduino/sketch_mar02a/sketch_mar02a.ino: In function 'void handleLogin()':
sketch_mar02a:312: error: 'username' was not declared in this scope
     if (server.arg("USERNAME") == username && server.arg("PASSWORD") == pass){                                              // USER AND PASS
                                   ^
/Users/benevolutionary/Documents/Arduino/sketch_mar02a/sketch_mar02a.ino: In function 'void setup()':
sketch_mar02a:618: error: 'username' was not declared in this scope
   username = eeprom_read_string();
   ^
exit status 1
expected ',' or ';' before 'String'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Nircek** [comment]
@benevolution Close this issue, because you got answer...
